[package]
name = "rai-lib"
version = "0.1.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]

[lib]
name = "rai_lib"
crate-type = ["staticlib"]

[dependencies]
nanocurrency-types = "0.3.10"
libc = "0.2.42"
serde_json = "1.0.20"
hex = "0.3.2"
